spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: 2944a893-8602-4a8f-bd06-9663d22177ed
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 2944a893-8602-4a8f-bd06-9663d22177ed
    alicloud:

      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: grainmall-hello1

  application:
    name: grainmall-third-party

server:
  port: 30000


